### ISSUE TITLE
Makefile in tarball

### ISSUE THREAD

**Issue by Leont** [davorg-cpan/amazon-sites#2]
It seems you're accidentally shipping a `Makefile` in your dist, when you should only be shipping a `Makefile.PL`. The probable cause is an incomplete `MANIFEST.SKIP` file, adding a `#!include_default` line should fix it

**Comment by davorg** [comment]
There are a couple of things I need to fix in the distribution - there's no README either. I'll do a better release later today

**Comment by davorg** [comment]
Fixed in 0.0.4
